# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_auto_20180301_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food_app.Restaurant')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
